### ISSUE TITLE
sync command not working for postgresql 

### ISSUE THREAD

**Issue by bhumipatel1512** [anlek/mongify#102]
i am trying to migrate postgresql database. sync command not working it gives an error like

/home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in `async_exec': PG::UndefinedColumn: ERROR:  column t.updated_at does not exist (ActiveRecord::StatementInvalid)
LINE 1: ....* FROM scsemp t, __mongify_sync_helper__ u WHERE t.updated_...
                                                             ^
: SELECT t.* FROM scsemp t, __mongify_sync_helper__ u WHERE t.updated_at > u.last_updated_at AND u.table_name = 'scsemp'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/postgresql_adapter.rb:1163:in`exec_no_cache'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract_adapter.rb:280:in`block in log'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activesupport-3.2.22.2/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract_adapter.rb:275:in`log'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/postgresql_adapter.rb:1262:in`select'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in`select_all'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:108:in `select_by_query'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/translation/sync.rb:61:in`block in sync_data'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/translation/sync.rb:58:in `each'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/translation/sync.rb:58:in`sync_data'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/translation/sync.rb:29:in `sync'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:71:in`execute'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/gems/mongify-1.2.4/bin/mongify:15:in`<top (required)>'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/bin/mongify:23:in `load'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/bin/mongify:23:in`<main>'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /home/bhumi/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in`<main>'

**Comment by anlek** [comment]
The issue is that `updated_at` is a required field for sync to work. See issue #109
