### ISSUE TITLE
Cannot connect to remote mysql server

### ISSUE THREAD

**Issue by dinhkhanh** [anlek/mongify#103]
I use mongify in localhost successfully. 

When I try to connect to a remote database server, an error occurs because of incorrect username.

My config file:

```ruby
sql_connection do
  adapter   "mysql"
  host      "10.10.10.10"
  username  'test@10.10.10.10'
  password  "test@123"
  database  "test"
end

mongodb_connection do
  host      "localhost"
  database  "test"
end
```
where `10.10.10.10` is my remote server IP address.

Output log:

```
$mongify ck database.conf translate.rb 
$/Users/myuser/.rvm/gems/ruby-2.3.0@global/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/mysql_adapter.rb:411:in `real_connect': Access denied for user 'news@10.10.10.10'@'10.8.8.42' (using password: YES) (Mysql::Error)
```
where `10.8.8.42` is my computer IP address.

Means mongify automatically append local IP into username.

How to change configuration file to make it work properly?

**Comment by bhumipatel1512** [comment]
use  $mongify check database.config  command for Checks connection for sql and no_sql databases

**Comment by anlek** [comment]
Remove the `@10.10.10.10` in the username.

Also, Mongify is NOT recommended to use via network to transfer data. The amount of read/writes the system does means it will take 10x or more to do the same action as if it was on a local system. Furthermore, Mongify is not able to recover from any network failures, so you might lose your progress hours into the translation.
I'd recommend you download a copy of the remote server and load it into your local db, do the translation and export the data back to the remote server.

Good luck,
Andrew

**Comment by dinhkhanh** [comment]
@anlek I thought I would do that way. Mongify "almost" everything in a local copy, then use `sync` to update if there is any new record in the remote database later.
