### ISSUE TITLE
NODatabaseError

### ISSUE THREAD

**Issue by deep406** [anlek/mongify#108]
I am trying to convert an sql database to mongodb. I installed ruby, gem, mysql, mongodb etc. after figuring out all the errors it has given so far but I can not understand this one. It does not recognize mysql database and gives this error:
'rescue in mysql2_connection' : Unknown database 'original' (ActiveRecord : : NoDatabaseError)
Any help will be appreciated. Thanks

**Comment by anlek** [comment]
Hey Deep406,
The database called `original` doesn't exist in your mysql database. You've likely specified this in the `database.config` file.

Hope that helps,
Andrew
