### ISSUE TITLE
Testing SQL Server Migration

### ISSUE THREAD

**Issue by obissick** [anlek/mongify#118]
Getting this error when trying to test connection.

obissick@mongify:~$ mongify check database.config
/home/obissick/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- tiny_tds (LoadError)
	from /home/obissick/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-sqlserver-adapter-4.2.15/lib/active_record/sqlserver_base.rb:9:in `sqlserver_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /home/obissick/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /home/obissick/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:567:in `retrieve_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.1/lib/active_record/connection_handling.rb:87:in `connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/database/sql_connection.rb:57:in `has_connection?'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:95:in `check_sql_connection'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:64:in `execute'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/lib/mongify/cli/application.rb:28:in `execute!'
	from /home/obissick/.rvm/gems/ruby-2.3.0/gems/mongify-1.3.0/bin/mongify:15:in `<top (required)>'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/mongify:23:in `load'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/mongify:23:in `<main>'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/obissick/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by anlek** [comment]
try installing `tiny_tds` by running `gem install tiny_tds`

**Comment by obissick** [comment]
That worked! thanks.

**Comment by anlek** [comment]
Glad to hear!
