### ISSUE TITLE
_id Field as Integer [Match _id with id field of MySQL]

### ISSUE THREAD

**Issue by kamrankhatti** [anlek/mongify#120]
Hello -

I ran mongify script to migrate MySQL data into MonogDB which works fine. However, I have `id` field in MySQL tables as `primary_key` but after mongify it overwrites with default mongify `_id` i.e `"_id" : ObjectId("58369f006ee5c61b9400000e"),` I don't want to overwrite this I need exactly same value of `primary_key` in `id` column in MySQL inot MongoDB `_id` something look like this:

MySQL `id: 123` should convert into MongoDb as `"_id" : ObjectId("123"),`

Any help?

**Comment by kamrankhatti** [comment]
Found the workaround which was already there in Mongify docs I missed that out :)
just need to add

`before_save do |row|`
`row._id = row.delete('pre_mongified_id')`
`end`

This `before_save` event does not allow Mongify to overwrite  MySQL `id` values.

Thanks anyways.

**Comment by srizviOfficial** [comment]
great, it works for me.
