### ISSUE TITLE
Can mongo db server be only in localhost?

### ISSUE THREAD

**Issue by devwwg** [anlek/mongify#123]
I'd need to make a connection to a mongodb on a remote server, but i misunderstand if mongify can only connect on localhost. 
In your documentation i didn't find any information about that. I just found examples with "host" and "database" properties.

Thanks,
Simone

**Comment by anlek** [comment]
Hey Simone,
It's not that Mongify can't connect to a remote server, inder HOST, you would give the IP/URL of your server in the world. However, keep in mind that moving data via the internet has lag/delays. Meaning that if you have a million record you want to convert, locally it could take 10 minutes, remotely it might take 10 hours (as mongify has to query to database to ensure the relationships are kept).

I highly recommend doing the conversion locally (as you're likely to run it a bunch of times before you can fine tune everything) and once your data is in your local mongodb instance, use `mongodump` to dump the database and use `mongorestore` on the remote server to import the data.

Good luck!
Andrew
