### ISSUE TITLE
Continue process from specific point

### ISSUE THREAD

**Issue by DarkN3ss61** [anlek/mongify#128]
Is there a way to continuing the process from a specific point  e.g 50% of the way?

A few time there will be timeout problems and the processing will stop, so that means I need to start from the beginning. but since it already did e.g 50% is there a way to start 50% into it so I don't need to redo the previous 50% that is already in the mongodb?

**Comment by srizviOfficial** [comment]
There is no such option for now. Either you can increase timeout to longer period to avoid it or may set batch option in configurations file in chunks to avoid timeouts.
