### ISSUE TITLE
error with mongo in proccess phase

### ISSUE THREAD

**Issue by isidioan** [anlek/mongify#129]
Hello , I get the error below when I try to proccess the translation file:

/var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1165:in `rescue in generate_indexes': Failed to create index {:name=>"pre_mongified_id_1", :key=>{"pre_mongified_id"=>1}} with the following error: Database command 'createIndexes' failed: not authorized on admin to execute command { createIndexes: "movies", indexes: [ { name: "pre_mongified_id_1", key: { pre_mongified_id: 1 } } ] } (Mongo::OperationFailure)
	from /var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1157:in `generate_indexes'
	from /var/lib/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:564:in `create_index'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/database/no_sql_connection.rb:159:in `create_pre_mongified_id_index'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:30:in `block in setup_db_index'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:29:in `each'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/translation/processor_common.rb:29:in `setup_db_index'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/translation/process.rb:13:in `process'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/cli/command/worker.rb:68:in `execute'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/lib/mongify/cli/application.rb:28:in `execute!'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.0/bin/mongify:15:in `<top (required)>'
	from /usr/local/bin/mongify:23:in `load'
	from /usr/local/bin/mongify:23:in `<main>'

my translation file is this one

table "genre", :ignore => true do
	column "id", :key, :as =>:integer
	column "movgenre", :text, :as => :string
end

table "genres", :ignore => true do
	column "id", :key, :as => :integer
	column "genre", :string
end

table "movie_genres", :ignore => true do
	column "movie", :integer
	column "genre", :integer
end

table "movies" do
	column "id", :key, :as => :integer
	column "title", :string
	column "release_date", :string
	column "video", :string
	column "IMDBURL", :string
end

table "ratings", :embed_in => :movies, :on => :movie do
	column "user", :integer, :references => :users
	column "movie", :integer, :references => :movies
	column "rating", :integer
	column "timestamp", :integer
end

table "users" do
	column "id", :key, :as => :integer
	column "age", :integer
	column "gender", :string
	column "occupation", :string
	column "zip_code", :string
end

any suggestions?

**Comment by anlek** [comment]
Seems like your mongoDB user doesn't have access to create indexes. Mongify requires to create indexes. Try fixing the permissions in MongoDB
