### ISSUE TITLE
translate string to array

### ISSUE THREAD

**Issue by guruward** [anlek/mongify#13]
in the mysql db I have an array stored as a string example "[3.3,3.2,3,2.8]" 
i would like to translate that  so its stored just as an array  {myArray: [3.3,3.2,3,2.8] }

is this possible ?

**Comment by Komalil** [comment]
Hello Anlek,

Is it possible to migrate whole table with out specifying column names in translation.rb file?
tried by keeping the below command in translation.rb file. but it is not inserting none of the records from mysql to mongo.

table "Test".
Would you help me to resolve the issue?

**Comment by anlek** [comment]
Hey @Komalil,
It is not an issue but a feature. Mongify ignores any columns you don't specify in the translation (as it wouldn't know how to translate them).
I'm not exactly sure why you don't want to use a translation, you can generate the translation table automatically via the `mongify translation database.config > translation.rb` command.

Good luck,
Andrew

**Comment by Komalil** [comment]
Hi Andrew,
Thanks for the email..
We need to migrate some of the mysql tables to mongo as per client
requirement. But mysql is having 4000+ tables. If i use below command, all
4000+ tables will be translated. My requiremnt i need to pick some of the
tables do the translation.
 mongify translation database.config > translation.rb
I have referred table.rb file, i have seen below commnad in that:
table "table_name"                                        # Does a straight
copy of the table
table "table_name", :embed_in => 'users' # Embeds table_name into users,
assuming a user_id is present in table_name.

the above commands i have tried in translation.rb file like:

table <mysql table name>

table <mysql table name>,:embed_in=> <Mongo collection name>
But it does not work.

Would you please suggest any required solution, how i need to migrate
specific tables to monog from out of mysql 4000+ tables?
Thanks in advance.

Regards,
Komali

**Comment by anlek** [comment]
I'm going to reply to this in #133 as it's more relevant there.
