### ISSUE TITLE
Migrate only one table from SQL Server to MongoDB

### ISSUE THREAD

**Issue by santoshdhegde** [anlek/mongify#137]
Hi Team,

I need to migrate only one table from SQL Server to MongoDB instead of entire data base. How/where I can configure that so that only 1 table migrates from sql server to mongodb. Now if I do mongify translation database.config > translation.rb and mongify process database.config translation.rb  it migrates entire data base. Please help me to provide the solution for this.

**Comment by anlek** [comment]
Mongify will only move tables you've specified. So remove any of the tables you don't want to be moved and leave only the table you do in the `translation.rb` file.
