### ISSUE TITLE
an error in your SQL syntax

### ISSUE THREAD

**Issue by guzishiwo** [anlek/mongify#145]
check the manual that corresponds to your MySQL server version for the right syntax to use near 'call' at line 1: SELECT COUNT(*) FROM call (ActiveRecord::StatementInvalid)

1. work mongify check database.config  --> success
when I exec the command "mongify process database.config translation_file.rb" run error 

os: osx10.12
database: mysql  Ver 14.14 Distrib 5.7.17, for osx10.12 (x86_64) using  EditLine wrapper

**Comment by anlek** [comment]
Seems like you have an issue with your `translation_file.rb` file. Please ensure you ran the generation script for the translation file. see more info at  http://mongify.com/getting_started.html
