### ISSUE TITLE
Select Data From Query

### ISSUE THREAD

**Issue by Icydillic** [anlek/mongify#146]
Hello All,

I was asking myself if it is also possible to select data from an sql db using a self defined query (a possible scenario could be an interface with transactions or something like this)?
I saw a method inside SqlConnection => select_by_query but it seems it is only for internal usage. Can you tell me if this is possible? 

Thank you very much!
Cheers,
Stefan

**Comment by anlek** [comment]
Sorry, there is no way to modify the select query, however, you can clone your database, delete all the items you don't want (via another tool) and migrate the rest using Mongify.
