### ISSUE TITLE
unable to run mongify against sqlserver

### ISSUE THREAD

**Issue by peddadap** [anlek/mongify#152]
Installed all gems but still version conflicts -- looks like 

root@WINDOWS-895AV1O:/mnt/c/projects/mongify# mongify check test.config
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'sqlserver' for database adapter, but the gem is not loaded. Add `gem 'activerecord-sqlserver-adapter'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_handling.rb:50:in `establish_connection'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:56:in `has_connection?'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:99:in `check_sql_connection'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:68:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/application.rb:28:in `execute!'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/mongify:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/mongify:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
root@WINDOWS-895AV1O:/mnt/c/projects/mongify# gem install activerecord-sqlserver-adapter -v 4.2.9
Successfully installed activerecord-sqlserver-adapter-4.2.9
Parsing documentation for activerecord-sqlserver-adapter-4.2.9
Done installing documentation for activerecord-sqlserver-adapter after 0 seconds
1 gem installed
root@WINDOWS-895AV1O:/mnt/c/projects/mongify# mongify check test.config
/usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'sqlserver' for database adapter, but the gem is not loaded. Add `gem 'activerecord-sqlserver-adapter'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
        from /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_handling.rb:50:in `establish_connection'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:56:in `has_connection?'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:99:in `check_sql_connection'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:68:in `execute'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/lib/mongify/cli/application.rb:28:in `execute!'
        from /usr/local/rvm/gems/ruby-2.4.1/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/mongify:23:in `load'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/mongify:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
root@WINDOWS-895AV1O:/mnt/c/projects/mongify#

**Comment by anlek** [comment]
try installing the activerecord-sqlserver-adapter gem: `gem install activerecord-sqlserver-adapter`

**Comment by peddadap** [comment]
Thx for the quick response, I did that, it didn't work,  I had to get the source and add a runtime dependency in the gem file , compile/build and installed it locally to make it work against sql server, I finally got the configuration working, yet to run full tests, the tools works great, I had used it earlier to port the data from postgres to mongo, this time we are doing from mssqlserver to mongo.

**Comment by anlek** [comment]
Wow, that sounds way more complicated than it should be. However, I'm glad you got it working! Good luck with your project.

**Comment by devabdicant** [comment]
I have the same problem now but I have no idea about how you managed to make it work. Can you help? thanks!
