### ISSUE TITLE
Unable to test database config

### ISSUE THREAD

**Issue by iammelvin** [anlek/mongify#160]
I installed ruby via rubyinstaller then added this gem 'activerecord-sqlserver-adapter' for sql server support.But once i run mongify check database.config nothing really happens in command line.It's just frozen is there anything more to be installed or configured.

I have the below in my config file

sql_connection do
  adapter   "sqlserver"
  host      "compserver"
  username  "sa"
  password  "sa123"
  database  "DEC19"
end

mongodb_connection do
  host "xxx.mongodb.net"
  port "27017"
  username "admin"
  password "S16d6s27m22."  
  database  "test"
end

What's wrong and how do i overcome this ? If i did how can i write translations for individual tables and not the whole database since there are many tables ?

Ps : I am using mongo atlas [database as service] version 3.4 

Thanks in advance :)

**Comment by anlek** [comment]
Please see #96.
