### ISSUE TITLE
Mongify has some issue with activeRecord 5.1

### ISSUE THREAD

**Issue by ektagarg** [anlek/mongify#168]
Am trying to use Mongify in my Ruby application. I have these gems installed:
1.  Active Record 5.1.6
2. mysql2 0.5.0
3. activerecord-mysql2-adapter 0.0.3 
4. mongify 1.3.0  
**My migrations file contains** : class CreatePosts < ActiveRecord::Migration[5.1]

**On running mongify check database.config it gives me this error** 

/home/xenial/.rvm/gems/ruby-2.4.1/gems/activerecord-5.1.6/lib/active_record/migration.rb:525:in `inherited': Directlyinheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for: (StandardError)

  class Mongify::Translation::Sync::SyncHelperMigrator < ActiveRecord::Migration[4.2]
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation/sync.rb:13:in `<module:Sync>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation/sync.rb:8:in `<class:Translation>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation/sync.rb:3:in `<module:Mongify>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation/sync.rb:2:in `<top (required)>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation.rb:3:in `require'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/translation.rb:3:in `<top (required)>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify.rb:13:in `require'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify.rb:13:in `<top (required)>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/cli.rb:1:in `require'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/lib/mongify/cli.rb:1:in `<top (required)>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/bin/mongify:10:in `require'
        from /home/xenial/.rvm/gems/ruby-2.4.1/gems/mongify-1.3.0/bin/mongify:10:in `<top (required)>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/bin/mongify:22:in `load'
        from /home/xenial/.rvm/gems/ruby-2.4.1/bin/mongify:22:in `<main>'
        from /home/xenial/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/xenial/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by anlek** [comment]
Mongify doesn't support ActiveRecord 5.1 at this moment, sorry!

**Comment by ektagarg** [comment]
So how can i implement Mongify ? I tried uninstalling ActiveRecord5.1 and installed ActiveRecord4.2 but still it gives me the same error.

**Comment by anlek** [comment]
You'd have to remove `[4.2]` out of your migration files and see how that helps
