### ISSUE TITLE
mysql : embedded tables

### ISSUE THREAD

**Issue by irfanjs** [anlek/mongify#171]
hi,
in the known issues section of documentation page, it is written that , 

> Can't do anything to an embedded table

for Mysql, there is no concept as embedded tables, but we have nested table structure where we have primary and foreign key relationships.
my query is , does Mongify is solution for such Mysql databases where we have tables which are related using primary/foreign key relations ?

please suggest 
Regards,

**Comment by anlek** [comment]
I'm not sure I fully understand your question and I'll try to do my best to answer what I think you're asking. Mongify will take your MySQL data and translate it into documents in MongoDB. You can specify relationships from MySQL to embed as an embedded document in MongoDB. However, currently, Mongify can ONLY embed 1 level deep. Please feel free to read the [docs](https://www.rubydoc.info/gems/mongify/) for more information. Good luck!

**Comment by irfanjs** [comment]
thanks. what do you mean by "Mongify can ONLY embed 1 level deep." can you please elaborate with example ?
