### ISSUE TITLE
Cannot process SQL because of backtick characters are missing

### ISSUE THREAD

**Issue by xkovacikm** [anlek/mongify#173]
Hi. I have **order** table in my SQL database. While executing `mongify process` command i get this error: 

**Mysql::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order' at line 1: SELECT COUNT(*) FROM order**

I think it's because **order** is reserved keyword in MySQL and query _SELECT COUNT(*) FROM order_ is incorrect. It should be _SELECT COUNT(*) FROM (backtick)order(backtick)_

(can't write backtick character here because of markdown)

translation.rb was created automatically by your `mongify translation` command.

Here is the whole error message:

/var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:346:in `query': Mysql::Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'order' at line 1: SELECT COUNT(*) FROM order (ActiveRecord::StatementInvalid)
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:346:in `block in exec_without_stmt'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
	from /var/lib/gems/2.3.0/gems/activesupport-4.2.10/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:345:in `exec_without_stmt'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:255:in `exec_query'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:356:in `select'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/mysql_adapter.rb:479:in `select'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:38:in `select_one'
	from /var/lib/gems/2.3.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:43:in `select_value'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/database/sql_connection.rb:114:in `count'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/database/sql_connection.rb:82:in `select_rows'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/process.rb:29:in `block in copy_data'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/process.rb:28:in `each'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/process.rb:28:in `copy_data'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/translation/process.rb:14:in `process'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/cli/command/worker.rb:72:in `execute'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/lib/mongify/cli/application.rb:28:in `execute!'
	from /var/lib/gems/2.3.0/gems/mongify-1.3.2/bin/mongify:17:in `<top (required)>'
	from /usr/local/bin/mongify:23:in `load'
	from /usr/local/bin/mongify:23:in `<main>'

Thank you ;)

**Comment by anlek** [comment]
Seems like it things `ORDER` as in a reserved word in SQL, my recommendation would be to rename the table to `orders` and see if you can work with that.
