### ISSUE TITLE
Level 2 embedding workaround?

### ISSUE THREAD

**Issue by steveo7** [anlek/mongify#30]
I see allow deeper embedding on the todo list.  In the mean time, would you have a recommended work around for one additional level...  embed into an embedded document?

**Comment by cbanbury** [comment]
@steveo7 Your workaround saved my day! 

After adding `row.improvement_details` would it be possible to remove that item from the `parent_row.improvement_details` (assuming a 1-1 mapping)?

You could then remove the array if empty to complete the cleanup. 

Sorry, I'm not that familiar with Ruby...

**Comment by steveo7** [comment]
Glad it helped.  I tried all kinds of different ways to delete from the parent row in the translation file, finally just gave up and included it in a cleanup step.  That was over a year ago, maybe something's changed.

**Comment by anlek** [comment]
Sorry to say, Not much has changed in the workings of Mongify over the year. :(
It's good that you guys have a way to work around this issue.
