### ISSUE TITLE
Process hangs when using sqlserver

### ISSUE THREAD

**Issue by jmorvan** [anlek/mongify#34]
When using the sql adapter the process hangs and I get the following error stack

        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/lib/mongify/database/sql_connection.rb:55:in `has_connection?'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/lib/mongify/cli/command/worker.rb:91:in `check_sql_connection'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/lib/mongify/cli/command/worker.rb:63:in `execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/lib/mongify/cli/application.rb:28:in `execute!'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/bin/mongify:15:in
        
        `<top (required)>'
        from C:/Ruby193/bin/mongify:23:in `load'
        from C:/Ruby193/bin/mongify:23:in `<main>'

or if I dont kill:
    
    C:/Ruby193/lib/ruby/gems/1.9.1/gems/mongify-1.0.1/lib/mongify/cli/application.rb:34: stack level too deep (SystemStackError)

Any idea?

**Comment by scookies** [comment]
I get to this page in search of looking for a way to connect sql server.  I installed activerecord-sqlserver-adapter but got the following while doing check database.config

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Please install the sqlserver adapter: `gem install activerecord-sqlserver-adapter` (Unable to activate activerecord-sqlserver-adapter-4.2.4, because activerecord-3.2.21 conflicts with activerecord (~> 4.2.1)) (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:50:in `resolve_hash_connection'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:29:in `spec'
	from /Library/Ruby/Gems/2.0.0/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:130:in `establish_connection'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:40:in `setup_connection_adapter'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:56:in `has_connection?'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:95:in `check_sql_connection'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:64:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
	from /Library/Ruby/Gems/2.0.0/gems/mongify-1.2.4/bin/mongify:15:in `<top (required)>'
	from /usr/bin/mongify:23:in `load'
	from /usr/bin/mongify:23:in `<main>'

**Comment by anlek** [comment]
Hey @scookies 
The issue is to sqlserver, I'm working on a mac and am unable to test on a windows machine. But if you get a rails up working with mysql server, the same connection string can be used in Mongify (as it uses activerecord under the hood).

**Comment by atn2017** [comment]
Any ideas on how to fix this? I remember using mongify long time ago and it was working ofr me, but it was a different OS and ruby. This time I am using Centos7. I tried it both with mysql and mysql2 gem, adjusting the configuration accordingly.

# mongify check database.config
SQL connection works
NoSQL connection works
# mongify translation database.config
/usr/local/share/gems/gems/mongify-1.3.1/lib/mongify/cli/application.rb:34: stack level too deep (SystemStackError)
# ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
# gem list

*** LOCAL GEMS ***

activemodel (4.2.9)
activerecord (4.2.9)
activerecord-mysql-adapter (0.0.1)
activerecord-mysql2-adapter (0.0.3)
activesupport (4.2.9)
arel (8.0.0, 6.0.4)
bigdecimal (1.2.6)
bson (1.12.5)
bson_ext (1.12.5)
builder (3.2.3)
concurrent-ruby (1.0.5)
highline (1.7.8)
i18n (0.8.6)
io-console (0.4.3)
json (1.8.1)
minitest (5.10.3)
mongify (1.3.1)
mongo (1.12.5)
mysql (2.9.1)
mysql2 (0.4.9)
psych (2.0.8)
rdoc (4.2.0)
thread_safe (0.3.6)
tzinfo (1.2.3)

**Comment by anlek** [comment]
Wow, that's odd. Do you have an ability to share more of the backtrace? Line 34 just re-raises the original exception.

**Comment by atn2017** [comment]
Actually, that is all of it.

If there is a switch I can use to enable a more detailed backtrace, I can try. I don't use ruby at all, but came across this project some time ago when I wsa trying to migrate the data from MySQL to MongoDB.

**Comment by anlek** [comment]
That's odd, maybe open a new issue as it doesn't fall under sqlserver.
I'll see if I can add a better error system and release a new version. Might take me a few days though.

**Comment by anlek** [comment]
Ok, I've released version `1.3.2`, removing the catch-all for exceptions. 
Please upgrade using `gem install mongify` and let me know what the new error is.
