### ISSUE TITLE
Mongify Killed after importing a large table

### ISSUE THREAD

**Issue by mosheka** [anlek/mongify#38]
We run an import of a set of tables,
After running several tables, the mongify stops with a "Killed" message after importing a large table. I repeated the process several times with the same result:

> mongify process database.config translation.rb
> Copying table1:                             (2/2) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table2:                           (22/22) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table3:                            (11/11) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table4:                             (5/5) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table5:                      (120/120) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:01
> Copying table6:                  (6144/6144) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:09
> Copying table7:                      (2/2) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table8:                    (9/9) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
> Copying table9:                           (191/191) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:02
> Copying table10:                 (165923/165923) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:09:45
> Killed

**Comment by srizviOfficial** [comment]
same issue we facing with sync command, it does not use batch instead insert all record at once which results in time out, we are migrating data from Microsoft sql server to mongoDB

**Comment by hammady** [comment]
I will see if I can fix this for sync.

**Comment by anlek** [comment]
@hammady Thanks for taking this on!
