### ISSUE TITLE
Problem with undefined method sql_conection

### ISSUE THREAD

**Issue by carcagi** [anlek/mongify#48]
I try to run the check database.config and I get the following errors.

[deprecated] I18n.enforce_available_locales will default to true in the future. If you really want to skip validation of your locale you can set I18n.enforce_available_locales = false to avoid this message.
/var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `instance_eval': undefined method `sql_conection' for #<Mongify::Configuration:0x00000001dffda8> (NoMethodError)
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `instance_eval'
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `parse'
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/cli/options.rb:78:in `config_file'
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/cli/options.rb:58:in `parse'
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/lib/mongify/cli/application.rb:27:in `execute!'
	from /var/lib/gems/1.9.1/gems/mongify-1.2.4/bin/mongify:15:in `<top (required)>'
	from /usr/local/bin/mongify:23:in `load'
	from /usr/local/bin/mongify:23:in `<main>'

I have the install activerecord-mysql-adapter installed.

**Comment by anlek** [comment]
Closing issue due to no responses
