### ISSUE TITLE
Table/Collection Doesn't Get Embedded or Imported

### ISSUE THREAD

**Issue by DanSchatz** [anlek/mongify#58]
Hi Anlek, I'm having a problem similar to #44. I thought the different syntax options might have something to do with it, but I've mixed and matched, and it doesn't look like it's related.

I've been using Mongify to work with some data that was originally formatted as standard SQL tables. I think it's much better suited for a NoSQL arrangement and thankfully I stumbled onto Mongify. Everything was working great: the databases were hooked up, translation files were being generated, and 'process' was sending the stream into Mongo. But as I was tweaking things, Mongify just stopped embedding the documents.

All the data gets sent into Mongo _except_ the table/collection that was to be embedded. It's not embedded in the intended parent collection and it doesn't come in on its own, either. All of a sudden, it worked for a single run again, but it went right back to not embedding. I've tried to tweak everything I can think of, but I just can't find the issue. What additional info can I pass on?

**Comment by anlek** [comment]
I'm sorry to hear you're having issues, Any chance you can provide me the translation file? If you prefer you can email me (andrew.kalek@anlek.com) with the information. I can try to see if I can figure it out.
