### ISSUE TITLE
Noob Question (How to create database.config and where to save it)

### ISSUE THREAD

**Issue by shoughun** [anlek/mongify#59]
Hi I am new here, already created database.config C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\activesupport-3.2.21\lib\active_support\values. Even changed the filename to database.config.rb but when I run mongify check database.config it says Database configuration file is miss or cannot be found.

Thank you in advance guys.

**Comment by shoughun** [comment]
Already fixed the issue. thanks.

**Comment by anlek** [comment]
Glad you got it figured out! :smile:
