### ISSUE TITLE
Embed in Document

### ISSUE THREAD

**Issue by AMS78** [anlek/mongify#68]
Hello, i have a MySql table users where column are id, firstname, lastname.

How can i transform it in document like : 
user : 
    _id
    infos :
        firstname
        lastname

I tried : 
column "firstname" , :string, :rename_to infos.firstname
column "firstname" , :string, :rename_to infos[firstname]
column "firstname" , :object, :rename_to infos.firstname
column "firstname" , :object, :rename_to infos[firstname]

before_save | row |
    row.infos.firstname = row.firstname
    row.infos[firstname] = row.firstanme
end

table "users",
    column "id", :key,  :rename_to => "_id"
    column "lastname",    :ignore
    column "firstname",   :ignore
end

table "users",
        :embed_in => 'users',                               
        :on => '_id',                                 
        :as => 'object' do
        column "id" , :ignore => true
        column "lastname",           :string, :rename_to => "lastname"
        column "firstname",        :string, :rename_to => "firstname"
end

Thanks a lot !

**Comment by anlek** [comment]
Hey @AMS78 Thanks a lot of tries.
I think the best approach would be `before_save`. Something like this:

```ruby
before_save | row |
  row.infos = {}
  row.infos[:firstname] = row.delete(:firstname)
end
```

Let me know if that works for you! :)
Good luck!

**Comment by AMS78** [comment]
PERFECT !

Thanks a lot !
