### ISSUE TITLE
Problems with Special Characters

### ISSUE THREAD

**Issue by nuk** [anlek/mongify#7]
Hi,

   I have a UTF8 Database in MySQL.
   It contains many entries with special characters ("maçã","evolução",etc).
   When mongify processes it it stumble on the following error from BSON:

/usr/lib/ruby/gems/1.8/gems/bson-1.4.0/lib/../lib/bson/bson_c.rb:24:in `serialize': String not valid UTF-8 (BSON::InvalidStringEncoding)

**Comment by smileisak** [comment]
Hi, 
I have the same issue but in my case i'm using Postgresql it shows me this :

/Library/Ruby/Gems/2.0.0/gems/bson-1.10.2/lib/bson/bson_c.rb:20:in `serialize': String not valid UTF-8 
(BSON::InvalidStringEncoding)

I added the "encoding "utf8" in the database.config" but it doesn't work.

Thanks for the attention

**Comment by anlek** [comment]
Hey @smileisak 
It should be said that you have to add 
```
# encoding  "utf8"
```
not just a bare ` encoding  "utf8"`

If this doesn't work, please submit a new trouble ticket. However at the moment there is a lot happening and I'm not sure I'll be able to tackle this any time soon. However I will accept any pull requests.

**Comment by kristjaningi** [comment]
@nuk @anlek

**Comment by vinpereira** [comment]
Hi there,

I'm using Mongify with MySQL and I'm having the String not valid UTF-8 (BSON::InvalidStringEncoding) error.

I try to put  '# encoding: UTF-8' (without quotes) at the top of database.config, but it does not work. Any help?

My gems:
*** LOCAL GEMS ***

activemodel (4.2.7.1)
activerecord (4.2.7.1)
activesupport (5.0.0.1, 4.2.7.1)
addressable (2.5.0)
arel (6.0.3)
backports (3.6.8)
bigdecimal (default: 1.2.8)
bson (1.12.5)
bson_ext (1.12.5)
builder (3.2.2)
bundler (1.13.6)
capybara (2.11.0, 2.10.2, 2.7.1)
capybara-screenshot (1.0.14)
childprocess (0.5.9)
cliver (0.3.2)
concurrent-ruby (1.0.2)
cucumber (2.4.0)
cucumber-core (1.5.0)
cucumber-wire (0.0.1)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
elasticsearch (5.0.0)
elasticsearch-api (5.0.0)
elasticsearch-transport (5.0.0)
faraday (0.10.0)
ffi (1.9.14 x64-mingw32)
gherkin (4.0.0)
highline (1.7.8)
i18n (0.7.0)
io-console (default: 0.4.5)
json (2.0.2, default: 1.8.3)
launchy (2.4.3)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.1.0)
minitest (5.10.1, 5.8.5)
mongify (1.3.1)
mongify-mongoid (1.0.4)
mongo (1.12.5)
multi_json (1.12.1)
multi_test (0.1.2)
multipart-post (2.0.0)
mysql2 (0.4.5 x64-mingw32)
net-telnet (0.1.1)
nokogiri (1.6.8.1 x64-mingw32)
poltergeist (1.11.0)
power_assert (0.2.6)
psych (default: 2.1.0)
public_suffix (2.0.4)
puma (3.6.2)
rack (2.0.1, 1.6.5)
rack-protection (1.5.3)
rack-test (0.6.3)
rake (10.4.2)
rdoc (default: 4.2.1)
rspec (3.5.0)
rspec-core (3.5.4)
rspec-expectations (3.5.0)
rspec-mocks (3.5.0)
rspec-support (3.5.0)
rubyzip (1.2.0)
selenium-webdriver (3.0.3)
sinatra (1.4.7)
sinatra-contrib (1.4.7)
syntax (1.2.1)
test-unit (3.1.5)
thread_safe (0.3.5)
tilt (2.0.5)
time_difference (0.5.0)
tzinfo (1.2.2)
websocket (1.2.3)
websocket-driver (0.6.4)
websocket-extensions (0.1.2)
xpath (2.0.0)

And the full error:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bson-1.12.5/lib/bson/bson_c.rb:20:in `serialize': String not valid UTF-8 (BSON::InvalidStringEncoding)              | ETA:  --:--:--
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bson-1.12.5/lib/bson/bson_c.rb:20:in `serialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/cursor.rb:654:in `construct_query_message'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/cursor.rb:549:in `block in send_initial_query'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:55:in `block in instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:20:in `instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:54:in `instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/cursor.rb:547:in `send_initial_query'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/cursor.rb:532:in `refresh'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/cursor.rb:139:in `next'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/db.rb:607:in `command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:314:in `block in send_write_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:55:in `block in instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:20:in `instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/functional/logging.rb:54:in `instrument'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:313:in `send_write_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1104:in `send_write'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:419:in `insert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:364:in `save'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/database/no_sql_connection.rb:128:in `upsert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/sync.rb:72:in `block (2 levels) in sync_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `block in each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/result.rb:51:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/sync.rb:64:in `block in sync_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/sync.rb:58:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/sync.rb:58:in `sync_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/sync.rb:29:in `sync'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:75:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/application.rb:28:in `execute!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
        from C:/Ruby23-x64/bin/mongify:22:in `load'
        from C:/Ruby23-x64/bin/mongify:22:in `<main>'

**Comment by Komalil** [comment]
Even if add encoding "utf8" still facing same problem: 
Here is my database.config file
sql_connection do
adapter "mysql2"
host "localhost"
username "*****"
password "******"
database "******"
encoding "utf8"
end

mongodb_connection do
host "localhost"
database "*****"
end


C:\Ruby23-x64>mongify process database.config translation.rb
Copying actor (1/1):                      (200/200) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
Copying actor_info (1/1):                 (200/200) 100% |ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo| Time: 00:00:00
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bson-1.12.5/lib/bson/bson_c.rb:20:in `serialize': String not valid UTF-8 (BSON::InvalidStringEncoding)oooooooooo| ETA:  00:00:00
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bson-1.12.5/lib/bson/bson_c.rb:20:in `serialize'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:65:in `block in batch_write_incremental'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:57:in `catch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection_writer.rb:57:in `batch_write_incremental'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:1184:in `batch_write'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongo-1.12.5/lib/mongo/collection.rb:411:in `insert'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/database/no_sql_connection.rb:101:in `insert_into'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/process.rb:36:in `block (2 levels) in copy_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:86:in `block in select_rows'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/range/each.rb:7:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/core_ext/range/each.rb:7:in `each_with_time_with_zone'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/database/sql_connection.rb:84:in `select_rows'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/process.rb:29:in `block in copy_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/process.rb:28:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/process.rb:28:in `copy_data'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/translation/process.rb:14:in `process'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/command/worker.rb:72:in `execute'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/lib/mongify/cli/application.rb:28:in `execute!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mongify-1.3.1/bin/mongify:15:in `<top (required)>'
        from C:/Ruby23-x64/bin/mongify:22:in `load'
        from C:/Ruby23-x64/bin/mongify:22:in `<main>'
