### ISSUE TITLE
Help embedding tables

### ISSUE THREAD

**Issue by afarqu** [anlek/mongify#71]
Hi

I am trying to embed MO_USAGEMSGS as an array into MO_USAGEDATA  on eventId as follows:

table "MO_USAGEDATA", :rename_to => 'TEST_DUMP' do
	column "EVENTID", :string, :rename_to => 'eventId', :references => :usageMessages
	column "CLIENTHOST", :string, :rename_to => 'clientIP'
	column "CLIENTHOST", :string, :rename_to => 'host'
end

table "MO_USAGEMSGS", :rename_to => 'usageMessages', :embed_in => :TEST_DUMP, :on => :eventId do
	column "EVENTID", :string, :rename_to => 'eventId'
	column "SEQ", :integer, :rename_to => 'sequence'
	column "MSGNAME", :string, :rename_to => 'messageName'
end

eventId is not a key in either table.

Thanks for any help that you can provide.
Alistair

**Comment by anlek** [comment]
I think this might be a limitation of the system, I believe it requires a key for one of the tables.
Maybe in your TEST_DUMP table, try to set eventID to a key (no references).
