### ISSUE TITLE
"Statement invalid" error with SQL Server 2012

### ISSUE THREAD

**Issue by jbwl** [anlek/mongify#72]
I have set up mongify to use with SQL Server 2012 using activerecord-sqlserver-adapter 3.2.13 (because mongify depends on activerecord ~> 3.2)

mongify check gives me an OK on both connections. When I try to process a translation (one table for testing), I get this strange error:

/home/user/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-3.2.13/lib/active_record/connection_adapters/sqlserver/database_statements.rb:416:in `each': TinyTds::Error: Adaptive Server connection timed out: EXEC sp_executesql N'SELECT COUNT(*) FROM MYBIGTABLE' (ActiveRecord::StatementInvalid)

(full dump here: https://gist.github.com/jbwl/62e8cb3a041499373d41)

The statement itself: 
`EXEC sp_executesql N'SELECT COUNT(*) FROM MYBIGTABLE' `
is valid and executes on other database clients with no problem, so I am thinking this error message is misleading and the problem is actually elsewhere.

**Comment by anlek** [comment]
I'm sorry to hear you're having issues. Sql Server is one of those things I'm unable to test as I don't have a Windows machine. However it seems the adapter is timing out. See if there is a way to add a longer timeout for `TinyTds`. Again, this is just a guess as I am not very familiar with Sql Server.
Good luck!

**Comment by jbwl** [comment]
Thank you! It was a timeout problem in the TinyTDS configuration options. For shell use of mongify, it is important to set a longer timeout on certain connections. This can be done in the freetds.conf file on Unix and Mac.

**Comment by anlek** [comment]
Thanks for sharing the solution!
