### ISSUE TITLE
`instance_eval': undefined method `adaptor' ... (NoMethodError)

### ISSUE THREAD

**Issue by crdiaz324** [anlek/mongify#73]
I cannot seem to find the issue here.  I have both activerecord-mysql-adapter and activerecord-mysql2-adapter gems installed but I am still getting the following error:

xonar:mongomigration dchen$ mongify check database.config 
/Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `instance_eval': undefined method `adaptor' for #<Mongify::Database::SqlConnection:0x000001010805a0> (NoMethodError)
	from (eval):2:in `block in parse'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:34:in `instance_exec'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:34:in `sql_connection'
	from (eval):1:in `parse'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `instance_eval'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/configuration.rb:14:in `parse'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/cli/options.rb:78:in `config_file'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/cli/options.rb:58:in `parse'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/cli/application.rb:27:in `execute!'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/bin/mongify:15:in `<top (required)>'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/bin/mongify:23:in `load'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/bin/mongify:23:in `<main>'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dchen/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by anlek** [comment]
Try using `adapter` instead of `adaptor`.

**Comment by crdiaz324** [comment]
Thanks Andrew!  My bad, I had a typo in my database.config, and typos are kind of hard to find at 1am :) 

Thanks again!

**Comment by anlek** [comment]
Glad I could help! Good luck!
