### ISSUE TITLE
wrong number of arguments (3 for 1..2) from activerecord-mysql2-adapter

### ISSUE THREAD

**Issue by kaloudis** [anlek/mongify#74]
evan@ubuntu:~/Desktop$ mongify process database.config translation.rb 
/home/evan/.rvm/gems/ruby-2.1.1/gems/activerecord-mysql2-adapter-0.0.3/lib/active_record/connection_adapters/mysql2_adapter.rb:614:in `select': wrong number of arguments (3 for 1..2) (ArgumentError)
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in`select_all'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in `select_all'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:24:in`select_one'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/database_statements.rb:30:in `select_value'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:114:in`count'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:82:in `select_rows'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/translation/process.rb:29:in`block in copy_data'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/translation/process.rb:28:in `each'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/translation/process.rb:28:in`copy_data'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/translation/process.rb:14:in `process'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:68:in`execute'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
    from /home/evan/.rvm/gems/ruby-2.1.1/gems/mongify-1.2.4/bin/mongify:15:in`<top (required)>'
    from /home/evan/.rvm/gems/ruby-2.1.1/bin/mongify:23:in `load'
    from /home/evan/.rvm/gems/ruby-2.1.1/bin/mongify:23:in`<main>'
    from /home/evan/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    from /home/evan/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in`<main>'

**Comment by kaloudis** [comment]
Hitting the same issue on both my OS X El Capitan system and my Xubuntu VM

**Comment by anlek** [comment]
Can you share your `database.config` (make sure to take out any **sensitive data**)

**Comment by dorothythurston** [comment]
@kaloudis were you ever able to resolve this issue?

**Comment by dorothythurston** [comment]
@anlek  Did you close this because you were able to resolve the issue or because of the lack of response from kaloudis?

**Comment by anlek** [comment]
I've been closing issues due to lack of response.

Is this still an issue for you?
