### ISSUE TITLE
mongify congig n translation file issues

### ISSUE THREAD

**Issue by hifzaa** [anlek/mongify#75]
hi. i m very new to ruby. i want to transfer my sql server data to mongodb.
i dont understand that how to write config and translation file n where to save it??? so that it will be access???
please help me i have very less time to complete my project.

**Comment by hifzaa** [comment]
@anlek  please help me

**Comment by anlek** [comment]
Hey, @hifzaa, I'm sorry to just be getting to your request, It's been a very busy last few months.
If you still need help, you should watch the video on mongify.com and follow the [getting started section](http://mongify.com/getting_started.html) of the site.
