### ISSUE TITLE
Connecting to mysql

### ISSUE THREAD

**Issue by qauseqazah** [anlek/mongify#76]
I have installed activerecord-mysql-adapter and mysql2 gems for connecting mongify to mysql.
but when i run command "mongify check database.config". It gives me following error:
Please install the my adapter:'gem install activerecord-mysql-adapter'

However gem list command shows both gems as installed.

**Comment by anlek** [comment]
Are you using some sort of Ruby Version Manager (like RVM or rbenv)?
Try using the "mysql" adapter vs "mysql2", see if that works better.

**Comment by flaforest77** [comment]
I have the same problem. I'm using ruby installer for windows and I have installed activerecord-mysql2-adapter and mysql2.
The version of mysql2 is 0.4.2, is it a problem ?

**Comment by anlek** [comment]
Unfortunately I don't have a Windows machine to test on, so I'm not sure. Maybe this might shed some light on it: https://stackoverflow.com/questions/4830396/problem-deploying-rails-3-with-passenger-missing-the-mysql-gem

**Comment by flaforest77** [comment]
I find the problem. When I install activerecord-mysql2-adapter, it also installs mysql2 version 0.4.2.
The solution is:
- Uninstall mysql2: gem uninstall mysql2
- Install the latest version 0.3.x: gem install -v mysql2 0.3.20

The problem is dependency.

**Comment by anlek** [comment]
Awesome, thanks for sharing that!
