### ISSUE TITLE
add auth function fail with mongo SCRAM-SHA-1 mechanism 

### ISSUE THREAD

**Issue by xudongli113** [anlek/mongify#78]
Hi All
I found the default mongo version mongify use is 1.10.2 which seems doesn't support mongodb 3.0 SCRAM-SHA-1 mechanism, am I right? because I am new to ruby, I change the gemspec file and seems it's not working, mongify still looking for 1.10.2 version,  can anyone can tell me how to update the mongo version that can be used by mongify? much appreciated

**Comment by anlek** [comment]
I'm sorry, this is outside my knowledge. I am unable to give you any direction for this.

**Comment by mete89** [comment]
Hi All,

Same problem here. I'm using mlab.com and it needs SCRAM-SHA-1. Is there a way to update mongo driver to 2.0 or 3.0?

**Comment by kinfkong** [comment]
Same here.

**Comment by anlek** [comment]
@kinfkong are you using mlab?

I'll schedule some time this weekend to review Mongify and see if updating games will work.
