### ISSUE TITLE
Error CURSOR_NOT_FOUND

### ISSUE THREAD

**Issue by NatsuOnFire** [anlek/mongify#80]
Hi,

After execute "mongify process database.config translation_file.rb", I have this error when mongify update references :
`C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/networking.rb:221:in 'check_response_flags': Query response returned CURSOR_NOT_FOUND. Either an invalid cursor was specified, or the cursor may have timed out on the server. (Mongo::OperationFailure)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/networking.rb:214:in 'receive_response_header'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/networking.rb:181:in 'receive'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/networking.rb:144:in 'receive_message'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/cursor.rb:596:in 'send_get_more'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/cursor.rb:526:in 'refresh'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/cursor.rb:136:in 'next'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/cursor.rb:334:in 'each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:47:in 'block in update_reference_ids'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:44:in 'each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:44:in 'update_reference_ids'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:15:in 'process'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:68:in 'execute'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in 'execute!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/bin/mongify:15:in '<top (required)>'
        from C:/Ruby22-x64/bin/mongify:23:in 'load'
        from C:/Ruby22-x64/bin/mongify:23:in '<main>'`

**Comment by anlek** [comment]
Can you share your transaction.rb file? (Remove any sensative data/columns)

**Comment by NatsuOnFire** [comment]
table "change_tag" do
	column "ct_rc_id", :integer, :references => "ct_rcs"
	column "ct_log_id", :integer, :references => "ct_logs"
	column "ct_rev_id", :integer, :references => "ct_revs"
	column "ct_tag", :binary
	column "ct_params", :binary
end

**Comment by anlek** [comment]
ok, So I assume it has something to do with ct_tag being binary, I haven't dealt with binary data before...
Was there any output from Mongify before the error or did it go straight to the error?

**Comment by NatsuOnFire** [comment]
I have already done a dump from another table with a binary type field and I have not had a problem.
I have no error before and I think the problem comes from references that do not exist.
