### ISSUE TITLE
String not valid UTF-8 (BSON::InvalidStringEncoding)

### ISSUE THREAD

**Issue by tjdavis1111** [anlek/mongify#86]
I am trying to use Mongify with SQL Server 2008.  The database is running SQL Server 2000 compatibility.  Here is my database.config:
sql_connection do
  adapter        "sqlserver"
  host             "lngoakcspsql005"
  username    "xxxxxxx"
  password     "xxxxxxx"
  database     "LNCSDashDemo_IA"
  batch_size    10000
  encoding      "utf8"
end

mongodb_connection do
  host        "localhost"
  database    "LNCSDashDemo_IA"
end_

One of the problems is that SQL Server does not use UTF-8, it uses UCS-2.  Is there an encoding setting for UCS-2?

Here is the full error:
C:\windows\system32>mongify process C:\Drive_D\Development\_MEAN\Mongify\database.config C:\Drive_D\Development\_MEAN\Mongify\translation_file_full.rb
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bson-1.10.2/lib/bson/bson_c.rb:20:in `serialize': String not valid UTF-8 (BSON::InvalidStringEncoding)
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/bson-1.10.2/lib/bson/bson_c.rb:20:in `serialize'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/collection_writer.rb:65:in `block in batch_write_incremental'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/collection_writer.rb:57:in `catch'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/collection_writer.rb:57:in `batch_write_incremental'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/collection.rb:1156:in `batch_write'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongo-1.10.2/lib/mongo/collection.rb:411:in `insert'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/database/no_sql_connection.rb:101:in `insert_into'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:36:in `block (2 levels) in copy_data'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:86:in `block in select_rows'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:84:in `each'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/database/sql_connection.rb:84:in `select_rows'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:29:in `block in copy_data'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:28:in `each'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:28:in `copy_data'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/translation/process.rb:14:in `process'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/cli/command/worker.rb:68:in `execute'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/lib/mongify/cli/application.rb:28:in `execute!'
	from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mongify-1.2.4/bin/mongify:15:in `<top (required)>'
	from C:/Ruby22-x64/bin/mongify:23:in `load'
	from C:/Ruby22-x64/bin/mongify:23:in `<main>'

Here are my gems:
*** LOCAL GEMS ***
activemodel (4.2.5.1, 3.2.22.1)
activerecord (4.2.5.1, 3.2.22.1)
activerecord-sqlserver-adapter (3.2.0)
activesupport (4.2.5.1, 3.2.22.1)
arel (6.0.3, 3.0.3)
bigdecimal (1.2.6)
bson (1.10.2)
bson_ext (1.10.2)
builder (3.2.2, 3.0.4)
highline (1.7.8)
i18n (0.7.0)
io-console (0.4.3)
json (1.8.3, 1.8.1)
mini_portile (0.6.2)
minitest (5.4.3)
mongify (1.2.4)
mongo (1.10.2)
multi_json (1.11.2)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
test-unit (3.0.8)
thread_safe (0.3.5)
tiny_tds (0.7.0 x64-mingw32)
tzinfo (1.2.2, 0.3.46)

Here is the table that is failing:
table "INT_AUX_ADDRESS" do
	column "ADDRESS_ID", :integer
	column "ADDRESS_SRC_ID", :integer
	column "OWN_LIST_ID", :integer, :references => "int_aux_listing"
	column "OWN_LIST_SRC_ID", :integer, :references => "int_aux_listing"
	column "ADDR_TYP_ID", :integer, :references => "int_address_typ"
	column "OWN_DIR_ID", :integer, :references => "int_aux_directory"
	column "OWN_DIR_SRC_ID", :integer, :references => "int_aux_directory"
	column "CREATE_ID", :integer, :references => "int_user"
	column "CREATE_DT", :datetime
	column "LAST_EDIT_ID", :integer, :references => "int_user"
	column "LAST_EDIT_NM", :string
	column "LAST_EDIT_DT", :datetime
	column "FORMAT", :string
	column "LABEL", :string
	column "LINE1", :string
	column "LINE2", :string
	column "LINE3", :string
	column "CITY", :string
	column "STATE", :string
	column "POSTAL_CD", :string
	column "COUNTRY", :string
	column "CHANGE_DT", :datetime
	column "TRAN_SRC_ID", :integer
	column "ADDR_SYS_ID", :integer
	column "SYS_ID", :integer
	column "SYS_SRC_ID", :integer
	column "SYS_IA_EDIT", :integer
	column "RESERVED", :string
	column "timestamp", :binary
	column "COUNTRY_ID", :integer, :references => "int_country"
end

Please let me know how to proceed.

Thank you.

**Comment by anlek** [comment]
Please check existing issues before posting. This seems very similar to issue #31. If the solution (at bottom of the page on #31) doesn't work, then feel free to reopen this issue.

**Comment by tjdavis1111** [comment]
Here is the "fix" from 31:
"Just a quick update, I verified all of mysql (client, server, tables, etc.) was happily speaking UTF8 and still encountered this issue. I resolved the issue by adding encoding "utf8" to database.config"

Here is my what I wrote:
"Here is my database.config:
sql_connection do
adapter "sqlserver"
host "lngoakcspsql005"
username "xxxxxxx"
password "xxxxxxx"
database "LNCSDashDemo_IA"
batch_size 10000
encoding "utf8"
end

mongodb_connection do
host "localhost"
database "LNCSDashDemo_IA"
end_"

SQLServer does not use UTF8.

**Comment by tjdavis1111** [comment]
How do I reopen this issue?

**Comment by tjdavis1111** [comment]
Also, #31 is for MySQL.  I am using Microsoft SQL Server.

**Comment by anlek** [comment]
Try putting `# encoding: UTF-8` at the very top of the file before anything else.
