### ISSUE TITLE
Embedding is not working 

### ISSUE THREAD

**Issue by lily2412** [anlek/mongify#92]
I have two tables 
table "DEFECT" do
	column "ID", :key, :as => :integer
	column "ProductID", :integer
	column "DefectNo", :string
	column "QualityDefectSeverityID", :integer
end

table "SEVERITY" , :embed_in=> :DEFECT , :on => :QualityDefectSeverityID do
	column "ID", :key , :rename_to => :QualityDefectSeverityID
	column "SeverityCode", :string

end

I have tried including a reference in defect and didn't work. 
Could you please help ?

**Comment by anlek** [comment]
I'm sorry, but I currently don't have time to support requests. Please read the [docs](http://www.rubydoc.info/gems/mongify/) for more help.
If you still have issues, please feel free to book time with me on [CodeMentor.io](http://codementor.io/anlek).
