### ISSUE TITLE
ActiveRecord 4 support?

### ISSUE THREAD

**Issue by joeauty** [anlek/mongify#93]
Hello,

I'd like to use Mongify with SQL Server 2014, and it looks like SQL Server 2014 requires activerecord-sqlserver-adapter-4.2.0 or higher, which doesn't work with Mongify, since Mongify will install 3.2.x.

`Please install the sqlserver adapter: `gem install activerecord-sqlserver-adapter` (Unable to activate activerecord-sqlserver-adapter-4.2.0, because activerecord-3.2.22.2 conflicts with activerecord (~> 4.2.0)) (LoadError)`

Is there an easy fix for this?

**Comment by anlek** [comment]
Hey @joeauty,
I've scheduled some time to work on Mongify this weekend, I'll update the gems and test to ensure it's fully working and let you know.

**Comment by anlek** [comment]
Hey @joeauty,
Just released version 1.3 of Mongify. It's been updated to work with Active Record 4.2.
let me know if you find any issues.
