### ISSUE TITLE
Unable to resolve dependencies: ubuntu

### ISSUE THREAD

**Issue by axlotl** [anlek/mongify#99]
```
gem install mongify
ERROR:  While executing gem ... (Gem::DependencyError)
Unable to resolve dependencies: mongify requires bson (>= 1.10.2); bson_ext requires bson (~> 1.12.5); mongo requires bson (~> 4.0)
```

`apt-cache search bson` doesn't seem to return anything of value except ruby-bson, which is installed. mongo works just fine.

(note successfully installed this gem locally on an up-to-date installation of OS X, but need to have it on the server)

**Comment by hejiann** [comment]
This is because the Ubuntu inbuilt ruby is lower version(1.9.3), you should install a newer version before gem install mongify:
$ curl -sSL https://get.rvm.io | bash -s stable
$ source ~/.rvm/scripts/rvm
$ rvm install 2.3.1
$ rvm use 2.3.1 --default
